apps:
  blender:
    cmds: ["{PROGRAMFILES}/Blender Foundation/Blender {version}/blender", "-P", "{STUDIO_REPO_PATH}/blender/extra/setup_environment.py"]
    version: 3.3
    env:
      STUDIO_ADDON_PATH : "{STUDIO_REPO_PATH}/blender/addons"
      STUDIO_STARTUP_PATH : "{STUDIO_REPO_PATH}/blender/startup"